---
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  builder: html
  configuration: docs/source/conf.py

python:
  install:
    - requirements: requirements/docs.txt
    - method: pip
      path: .
