version: 2.1
workflows:
  version: 2
  build:
    jobs:
      - python2
      - python3
jobs:
  python2:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt -e .
      - run:
          name: Static analysis
          command: |
            . venv/bin/activate
            flake8 src tests docs
      - run:
          name: Test cases
          command: |
            . venv/bin/activate
            pytest tests


  python3:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt -e .
      - run:
          name: Static analysis
          command: |
            . venv/bin/activate
            flake8 src tests docs
      - run:
          name: Test cases
          command: |
            . venv/bin/activate
            pytest tests
