name: ReleaseNotice
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: post a message to slack
      uses: tokorom/action-slack-incoming-webhook@main
      env:
        INCOMING_WEBHOOK_URL: ${{ secrets.INCOMING_WEBHOOK_URL }}
      with:
        text: "Testing GH to Slack Webhook"
